[mypy]
plugins = pydantic.mypy
ignore_missing_imports = False
# mypy_path = src,shared
mypy_path = .
exclude = /src/lib/thread_utils



# An error with paramiko stubs; the effect of this is modules cannot be in different directories, which we don't need
no_namespace_packages = True
# must be False without namespace packages
explicit_package_bases = False


follow_imports = normal
warn_return_any = False
disallow_untyped_defs = True
#pydantic having strange errors
#disallow_any_unimported = True
disallow_any_expr = False
disallow_any_decorated = True
disallow_any_explicit = True
disallow_any_generics = True
# Not all errors have columns and this makes the regex in tasks.json easier
show_column_numbers = False
implicit_reexport = False
check_untyped_defs = True
no_implicit_optional=True
disallow_untyped_calls=True
strict=True


[pydantic-mypy]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True