x-shared-environment: &server-shared-environment
  DB_HOST: '${DB_HOST}'
  DB_USER: '${DB_USER}'
  DB_PORT: ${DB_PORT}
  DB_NAME: '${DB_NAME}'
  PGPASS_PATH: '${PGPASS_PATH}'
  DB_PWD: '${DB_PWD}'

  REDIS_INTERNAL_PORT: ${REDIS_INTERNAL_PORT}
  REDIS_HOSTNAME: '${REDIS_HOSTNAME}'
  REDIS_PASSWORD: '${REDIS_PASSWORD}'

  DOCKER_IMPORTER_HOSTNAME: '${DOCKER_IMPORTER_HOSTNAME}'
  RUN_NODEJS_OUTSIDE_OF_DOCKER: '${RUN_NODEJS_OUTSIDE_OF_DOCKER:-false}'
  IMPORTER_PUBLISHED_PORT: ${IMPORTER_PUBLISHED_PORT}

  ADMIN_SESSION_MAX_AGE: ${ADMIN_SESSION_MAX_AGE:-300000} # 5 min default
  ADMIN_SESSION_SECRET: '${ADMIN_SESSION_SECRET}'
  ADMIN_SESSION_HTTP_ONLY: '${ADMIN_SESSION_HTTP_ONLY}'
  ADMIN_SESSION_SIGNED: '${ADMIN_SESSION_SIGNED}'
  ADMIN_SESSION_ROLLING: ${ADMIN_SESSION_ROLLING:-false}
  ADMIN_SESSION_RENEW: '${ADMIN_SESSION_RENEW}'
  ADMIN_SESSION_SECURE: '${ADMIN_SESSION_SECURE}'

  SMTP_HOST: '${SMTP_HOST}'
  SMTP_PORT: ${SMTP_PORT}
  SMTP_FROM: '${SMTP_FROM}'
  SMTP_ADMIN: '${SMTP_ADMIN}'
  SMTP_USER: '${SMTP_USER}'
  GMT_SMTP_PASSWORD: '${GMT_SMTP_PASSWORD}'

  KEYCLOAK_GMT_REALM_NAME: '${KEYCLOAK_GMT_REALM_NAME}'

  KEYCLOAK_HOST: '${KEYCLOAK_HOST}'
  KEYCLOAK_EXTERNAL_HOST: '${KEYCLOAK_EXTERNAL_HOST}'
  KEYCLOAK_INTERNAL_BASE_URL: '${KEYCLOAK_INTERNAL_BASE_URL}'
  KEYCLOAK_EXTERNAL_BASE_URL: '${KEYCLOAK_EXTERNAL_BASE_URL}'

  KEYCLOAK_WEB_CLIENT_NAME: '${KEYCLOAK_WEB_CLIENT_NAME}'

  KEYCLOAK_NODEJS_ADMIN_USERNAME: '${KEYCLOAK_NODEJS_ADMIN_USERNAME}'
  GMT_KEYCLOAK_GMT_ADMIN_USER_PASSWORD: '${GMT_KEYCLOAK_GMT_ADMIN_USER_PASSWORD}'

  OPERATIONAL_BOUNDARY_LEVEL: ${OPERATIONAL_BOUNDARY_LEVEL}
  PWA_URL: '${PWA_URL}'

services:
  server:
    image: "${DOCKER_IMAGES_PREFIX}server:${DOCKER_IMAGE_TAG}"
    networks:
      gmt-net:
    environment:
      <<: *server-shared-environment

  queues:
    image: "${DOCKER_IMAGES_PREFIX}server:${DOCKER_IMAGE_TAG}"
    command: "dumb-init npm run start-queues:prod"
    entrypoint: ["/usr/src/app/docker/custom-entrypoint.sh"]
    networks:
      gmt-net:
    environment:
      <<: *server-shared-environment

  redis:
      image: redis
      environment:
        REDIS_HOSTNAME: '${REDIS_HOSTNAME}'
        ALLOW_EMPTY_PASSWORD: '${ALLOW_EMPTY_PASSWORD}'
      networks:
        gmt-net:
           aliases:
              - "${REDIS_HOSTNAME}"
      volumes:
        - "/mnt/gmt/${ENV_NAME}_redis_data:/data:rw"

  pwa:
    image: "${DOCKER_IMAGES_PREFIX}pwa:${DOCKER_IMAGE_TAG}"

    environment:
      # everything in config template substitution config.json
      IS_PROD: ${IS_PROD}
      DISABLE_SYNC: ${DISABLE_SYNC}
      GA_TRACKING_CODE: ${GA_TRACKING_CODE}
      API_URL: ${API_URL}
      GEOSERVER_URL: ${GEOSERVER_URL}
      APP_VERSION: ${APP_VERSION}
      ENV_NAME: '${ENV_NAME}'
      DEVELOPER_MODE: ${DEVELOPER_MODE}
      ENV_COLOR: ${ENV_COLOR}
      GMT_DOC_ROOT: ${GMT_DOC_ROOT}
      KEYCLOAK_EXTERNAL_BASE_URL: ${KEYCLOAK_EXTERNAL_BASE_URL}
      KEYCLOAK_WEB_CLIENT_NAME: ${KEYCLOAK_WEB_CLIENT_NAME}
      KEYCLOAK_PWA_SCOPE: ${KEYCLOAK_PWA_SCOPE}
      OPERATIONAL_BOUNDARY_LEVEL: ${OPERATIONAL_BOUNDARY_LEVEL}
      BOUNDARY_LEVEL_LABELS: ${BOUNDARY_LEVEL_LABELS}
      DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE}
      SUGGESTED_LOCATION_ACCURACY_M: ${SUGGESTED_LOCATION_ACCURACY_M}
      DEV_TOOLS_PIN_CODE: ${DEV_TOOLS_PIN_CODE}
      MIN_FIXED_POST_BUFFER_M: ${MIN_FIXED_POST_BUFFER_M}
      MAX_FIXED_POST_BUFFER_M: ${MAX_FIXED_POST_BUFFER_M}
      TARGET_POPULATION_PERCENTAGE: ${TARGET_POPULATION_PERCENTAGE}
      COVERAGE_WEIGHT_STRATEGY_FIXED_POST: ${COVERAGE_WEIGHT_STRATEGY_FIXED_POST}
      COVERAGE_WEIGHT_STRATEGY_OUTREACH: ${COVERAGE_WEIGHT_STRATEGY_OUTREACH}
      COVERAGE_WEIGHT_FREQUENCY_UNKNOWN: ${COVERAGE_WEIGHT_FREQUENCY_UNKNOWN}
      COVERAGE_WEIGHT_FREQUENCY_ONCE_PER_MONTH: ${COVERAGE_WEIGHT_FREQUENCY_ONCE_PER_MONTH}
      COVERAGE_WEIGHT_FREQUENCY_TWICE_PER_MONTH: ${COVERAGE_WEIGHT_FREQUENCY_TWICE_PER_MONTH}
      COVERAGE_WEIGHT_FREQUENCY_THREE_PER_MONTH: ${COVERAGE_WEIGHT_FREQUENCY_THREE_PER_MONTH}
      COVERAGE_WEIGHT_FREQUENCY_ONCE_PER_WEEK: ${COVERAGE_WEIGHT_FREQUENCY_ONCE_PER_WEEK}
      COVERAGE_WEIGHT_FREQUENCY_TWICE_PER_WEEK: ${COVERAGE_WEIGHT_FREQUENCY_TWICE_PER_WEEK}
      COVERAGE_WEIGHT_FREQUENCY_THREE_PER_WEEK: ${COVERAGE_WEIGHT_FREQUENCY_THREE_PER_WEEK}
      COVERAGE_WEIGHT_FREQUENCY_FOUR_PER_WEEK: ${COVERAGE_WEIGHT_FREQUENCY_FOUR_PER_WEEK}
      COVERAGE_WEIGHT_FREQUENCY_FIVE_PER_WEEK: ${COVERAGE_WEIGHT_FREQUENCY_FIVE_PER_WEEK}
      COVERAGE_WEIGHT_FREQUENCY_SIX_PER_WEEK: ${COVERAGE_WEIGHT_FREQUENCY_SIX_PER_WEEK}
      COVERAGE_WEIGHT_FREQUENCY_DAILY: ${COVERAGE_WEIGHT_FREQUENCY_DAILY}
      COVERAGE_WEIGHT_FREQUENCY_OTHER: ${COVERAGE_WEIGHT_FREQUENCY_OTHER}
      COVERAGE_WEIGHT_BOUNDARY_INSIDE: ${COVERAGE_WEIGHT_BOUNDARY_INSIDE}
      COVERAGE_WEIGHT_BOUNDARY_OUTSIDE: ${COVERAGE_WEIGHT_BOUNDARY_OUTSIDE}
      COVERAGE_WEIGHT_DISTANCE_BREAKPOINTS: ${COVERAGE_WEIGHT_DISTANCE_BREAKPOINTS}
      COVERAGE_WEIGHT_MIN_PERCENTAGE: ${COVERAGE_WEIGHT_MIN_PERCENTAGE}
      COVERAGE_WEIGHT_MIN_SETT_PERCENTAGE: ${COVERAGE_WEIGHT_MIN_SETT_PERCENTAGE}
      COVERAGE_WEIGHT_MIN_SETT_POP: ${COVERAGE_WEIGHT_MIN_SETT_POP}

      # startup script
      CONFIG_TEMPLATE_FILE_OVERRIDE: '${CONFIG_TEMPLATE_FILE_OVERRIDE}'
      MANIFEST_TEMPLATE_FILE_OVERRIDE: '${MANIFEST_TEMPLATE_FILE_OVERRIDE}'
      CONFIG_FILE_DEST_OVERRIDE: '${CONFIG_FILE_DEST_OVERRIDE}'
      MANIFEST_FILE_DEST_OVERRIDE: '${MANIFEST_FILE_DEST_OVERRIDE}'
      ANGULAR_SERVE_PATH: '${ANGULAR_SERVE_PATH}'
      ANGULAR_DO_SUBSTITUTE_CONFIG: '${ANGULAR_DO_SUBSTITUTE_CONFIG}'
    networks:
      gmt-net:

  importer :
    image : "${DOCKER_IMAGES_PREFIX}importer:${DOCKER_IMAGE_TAG}"
    environment :
      DB_HOST: '${DB_HOST}'
      DB_USER: '${DB_USER}'
      DB_NAME: '${DB_NAME}'
      PGPASS_PATH: '${PGPASS_PATH}'
      DB_PWD: '${DB_PWD}'
      DB_PORT: ${DB_PORT}
      OPERATIONAL_BOUNDARY_LEVEL: ${OPERATIONAL_BOUNDARY_LEVEL}
      BOUNDARY_LEVEL_LABELS: ${BOUNDARY_LEVEL_LABELS}
    networks :
      gmt-net :
        aliases:
          - "${DOCKER_IMPORTER_HOSTNAME}"

# Interferes with docker swarm for some reason
#    depends_on :
#    - db

  keycloak:
    image: "${DOCKER_IMAGES_PREFIX}keycloak:${DOCKER_IMAGE_TAG}"
#    env_file:
#      - config/${CONFIG_FILE_NAME}.env
#      - config/secrets.${CONFIG_FILE_NAME}.env
    environment:
      JAVA_OPTS: "-Xms${KEYCLOAK_JVM_INITIAL_MEMORY:-256M} -Xmx${KEYCLOAK_JVM_MAXIMUM_MEMORY:-4G}"
      # used by keycloak container
      KEYCLOAK_USER: '${KEYCLOAK_USER}'
      KEYCLOAK_PASSWORD: '${GMT_KEYCLOAK_GMT_ADMIN_USER_PASSWORD}'  # typically set as the admin password
      KEYCLOAK_IMPORT: '${KEYCLOAK_IMPORT}'
      KEYCLOAK_LOGLEVEL: '${KEYCLOAK_LOGLEVEL:-DEBUG}'  # optional
      KEYCLOAK_FRONTEND_URL: '${KEYCLOAK_FRONTEND_URL}'

      KEYCLOAK_PROXY_ADDRESS_FORWARDING: ${KEYCLOAK_PROXY_ADDRESS_FORWARDING}
      DB_VENDOR: '${DB_VENDOR}'  # e.g. postgres
      DB_ADDR: '${DB_ADDR}'
      DB_PORT: ${DB_PORT}
      DB_USER: '${DB_USER}'
      KEYCLOAK_PWA_SCOPE: '${KEYCLOAK_PWA_SCOPE}'
      DB_PASSWORD: '${DB_PASSWORD}'
      PROXY_ADDRESS_FORWARDING: '${PROXY_ADDRESS_FORWARDING}'
      DB_KEYCLOAK_DATABASE_NAME: '${DB_KEYCLOAK_DATABASE_NAME}'
      DB_DATABASE: '${DB_DATABASE}'


      # in load secrets
      SECRETS_ROOT: '${SECRETS_ROOT}'

      # in prereq script
      DB_PWD: '${DB_PWD}'
      DB_USER_FOR_CREATE: '${DB_USER_FOR_CREATE}'
      DB_KEYCLOAK_DATABASE_USER_FOR_CREATE: '${DB_KEYCLOAK_DATABASE_USER_FOR_CREATE}'
      DB_KEYCLOAK_DATABASE_PASSWORD: '${DB_KEYCLOAK_DATABASE_PASSWORD}'

      # used in wait for postgres
      DB_HOST: '${DB_HOST}'

      # used in 02_add-gmt-users
      GMT_ADMIN_USER: '${GMT_ADMIN_USER}'
      QUEUE_ADMIN_USER: '${QUEUE_ADMIN_USER}'
      GMT_EDITOR_USER: '${GMT_EDITOR_USER}'
      GMT_READER_USER: '${GMT_READER_USER}'
      GMT_USERS_ADMIN: '${GMT_USERS_ADMIN}'

      KEYCLOAK_GMT_REALM_USER: '${KEYCLOAK_GMT_REALM_USER}'
      KEYCLOAK_GMT_REALM_NAME: '${KEYCLOAK_GMT_REALM_NAME}'

      GMT_KEYCLOAK_ADMIN_USER_PASSWORD: '${GMT_KEYCLOAK_ADMIN_USER_PASSWORD}'
      GMT_KEYCLOAK_GMT_ADMIN_USER_PASSWORD: '${GMT_KEYCLOAK_GMT_ADMIN_USER_PASSWORD}'
      QUEUE_ADMIN_USER_PASSWORD: '${QUEUE_ADMIN_USER_PASSWORD}'
      GMT_USER_PASSWORD: '${GMT_USER_PASSWORD}'


      # in realm template
      KEYCLOAK_SSO_SESSION_IDLE_TIMEOUT: ${KEYCLOAK_SSO_SESSION_IDLE_TIMEOUT}
      CLIENT_ACCOUNT_SECRET: '${CLIENT_ACCOUNT_SECRET}'
      CLIENT_ADMIN_CLI_SECRET: '${CLIENT_ADMIN_CLI_SECRET}'
      CLIENT_BROKER_SECRET: '${CLIENT_BROKER_SECRET}'
      CLIENT_DASHBOARD_SECRET: '${CLIENT_DASHBOARD_SECRET}'
      CLIENT_REALM_MANAGEMENT_SECRET: '${CLIENT_REALM_MANAGEMENT_SECRET}'
      CLIENT_SECURITY_ADMIN_CONSOLE_SECRET: '${CLIENT_SECURITY_ADMIN_CONSOLE_SECRET}'
      IDP_GOOGLE_CLIENT_SECRET: '${IDP_GOOGLE_CLIENT_SECRET}'
      IDP_GOOGLE_CLIENT_ID: '${IDP_GOOGLE_CLIENT_ID}'

      KEY_PROVIDER_AES_GENERATED_KID: '${KEY_PROVIDER_AES_GENERATED_KID}'
      KEY_PROVIDER_AES_GENERATED_SECRET: '${KEY_PROVIDER_AES_GENERATED_SECRET}'
      KEY_PROVIDER_HMAC_GENERATED_KID: '${KEY_PROVIDER_HMAC_GENERATED_KID}'
      KEY_PROVIDER_HMAC_GENERATED_SECRET: '${KEY_PROVIDER_HMAC_GENERATED_SECRET}'
      KEY_PROVIDER_RSA_GENERATED_CERTIFICATE: '${KEY_PROVIDER_RSA_GENERATED_CERTIFICATE}'
      KEY_PROVIDER_RSA_GENERATED_PRIVATE_KEY: '${KEY_PROVIDER_RSA_GENERATED_PRIVATE_KEY}'
      CLIENT_DASHBOARD_ROOT_URL: '${CLIENT_DASHBOARD_ROOT_URL}'
      CLIENT_DASHBOARD_ADMIN_URL: '${CLIENT_DASHBOARD_ADMIN_URL}'
      CLIENT_DASHBOARD_REDIRECT_URIS: '${CLIENT_DASHBOARD_REDIRECT_URIS}'
      CLIENT_DASHBOARD_WEB_ORIGINS: '${CLIENT_DASHBOARD_WEB_ORIGINS}'
      CLIENT_API_REDIRECT_URIS: '${CLIENT_API_REDIRECT_URIS}'
      CLIENT_API_WEB_ORIGINS: '${CLIENT_API_WEB_ORIGINS}'
      KEYCLOAK_EXTERNAL_BASE_URL: '${KEYCLOAK_EXTERNAL_BASE_URL}'
      CLIENT_MOBILE_REDIRECT_URIS: '${CLIENT_MOBILE_REDIRECT_URIS}'
      CLIENT_MOBILE_WEB_ORIGINS: '${CLIENT_MOBILE_WEB_ORIGINS}'
      CLIENT_SECURITY_ADMIN_CONSOLE_REDIRECT_URIS: '${CLIENT_SECURITY_ADMIN_CONSOLE_REDIRECT_URIS}'
      CLIENT_SECURITY_ADMIN_CONSOLE_WEB_ORIGINS: '${CLIENT_SECURITY_ADMIN_CONSOLE_WEB_ORIGINS}'
      SMTP_STARTTLS: '${SMTP_STARTTLS}'
      SMTP_AUTH: '${SMTP_AUTH}'
      SMTP_ENVELOPE_FROM: '${SMTP_ENVELOPE_FROM}'
      SMTP_SSL: '${SMTP_SSL}'
      GMT_SMTP_PASSWORD: '${GMT_SMTP_PASSWORD}'
      SMTP_PORT: ${SMTP_PORT}
      SMTP_HOST: '${SMTP_HOST}'
      SMTP_REPLY_TO_DISPLAY_NAME: '${SMTP_REPLY_TO_DISPLAY_NAME}'
      SMTP_REPLY_TO: '${SMTP_REPLY_TO}'
      SMTP_FROM_DISPLAY_NAME: '${SMTP_FROM_DISPLAY_NAME}'
      SMTP_FROM: '${SMTP_FROM}'
      SMTP_USER: '${SMTP_USER}'



    command: [
      "-b", "0.0.0.0",
      "-Dkeycloak.profile.feature.scripts=enabled",
      "-Dkeycloak.profile.feature.upload_scripts=enabled",
      "-Dkeycloak.profile.feature.token_exchange=enabled",
      "${KEYCLOAK_START_ON_CUSTOM_PORT_COMMAND}",
      "-Dkeycloak.profile=preview"
    ]
    networks :
      gmt-net :

networks:
  gmt-net:
    name: '${DOCKER_NETWORK_NAME}'
    external: '${DOCKER_NETWORK_IS_EXTERNAL}'
