parent=base
styles=css/gmt.css
scripts=js/gmt.js
meta=viewport==width=device-width,initial-scale=1

kcLoginClass=login-pf-page
kcFormCardClass=card-pf

kcFormSocialAccountListClass=socials-container
kcFormSocialAccountListLinkClass=social-container

kcFormGroupClass=form-group
kcFormGroupClassLogin=form-group-login
