#!/bin/bash

sed "\
s/KEYCLOAK_SSO_SESSION_IDLE_TIMEOUT/$KEYCLOAK_SSO_SESSION_IDLE_TIMEOUT/;\
s/CLIENT_ACCOUNT_SECRET/$CLIENT_ACCOUNT_SECRET/;\
s/CLIENT_ADMIN_CLI_SECRET/$CLIENT_ADMIN_CLI_SECRET/;\
s/CLIENT_BROKER_SECRET/$CLIENT_BROKER_SECRET/;\
s/CLIENT_DASHBOARD_SECRET/$CLIENT_DASHBOARD_SECRET/;\
s/CLIENT_REALM_MANAGEMENT_SECRET/$CLIENT_REALM_MANAGEMENT_SECRET/;\
s/CLIENT_SECURITY_ADMIN_CONSOLE_SECRET/$CLIENT_SECURITY_ADMIN_CONSOLE_SECRET/;\
s/IDP_GOOGLE_CLIENT_SECRET/$IDP_GOOGLE_CLIENT_SECRET/;\
s/IDP_GOOGLE_CLIENT_ID/$IDP_GOOGLE_CLIENT_ID/;\
s/KEYCLOAK_FRONTEND_URL/KEYCLOAK_FRONTEND_URL/;\
s/KEY_PROVIDER_AES_GENERATED_KID/$KEY_PROVIDER_AES_GENERATED_KID/;\
s/KEY_PROVIDER_AES_GENERATED_SECRET/$KEY_PROVIDER_AES_GENERATED_SECRET/;\
s/KEY_PROVIDER_HMAC_GENERATED_KID/$KEY_PROVIDER_HMAC_GENERATED_KID/;\
s/KEY_PROVIDER_HMAC_GENERATED_SECRET/$KEY_PROVIDER_HMAC_GENERATED_SECRET/;\
s#KEY_PROVIDER_RSA_GENERATED_CERTIFICATE#$KEY_PROVIDER_RSA_GENERATED_CERTIFICATE#;\
s#KEY_PROVIDER_RSA_GENERATED_PRIVATE_KEY#$KEY_PROVIDER_RSA_GENERATED_PRIVATE_KEY#;\
s#CLIENT_DASHBOARD_ROOT_URL#$(echo -n "${CLIENT_DASHBOARD_ROOT_URL}")#;\
s#CLIENT_DASHBOARD_ADMIN_URL#$(echo -n "${CLIENT_DASHBOARD_ADMIN_URL}")#;\
s#CLIENT_DASHBOARD_REDIRECT_URIS#$(echo -n "${CLIENT_DASHBOARD_REDIRECT_URIS}")#;\
s#CLIENT_DASHBOARD_WEB_ORIGINS#$(echo -n "${CLIENT_DASHBOARD_WEB_ORIGINS}")#;\
s#CLIENT_API_REDIRECT_URIS#$(echo -n "${CLIENT_API_REDIRECT_URIS}")#;\
s#CLIENT_API_WEB_ORIGINS#$(echo -n "${CLIENT_API_WEB_ORIGINS}")#;\
s#KEYCLOAK_EXTERNAL_BASE_URL#$(echo -n "${KEYCLOAK_EXTERNAL_BASE_URL}")#;\
s#CLIENT_MOBILE_REDIRECT_URIS#$(echo -n "${CLIENT_MOBILE_REDIRECT_URIS}")#;\
s#CLIENT_MOBILE_WEB_ORIGINS#$(echo -n "${CLIENT_MOBILE_WEB_ORIGINS}")#;\
s#CLIENT_SECURITY_ADMIN_CONSOLE_REDIRECT_URIS#$(echo -n "${CLIENT_SECURITY_ADMIN_CONSOLE_REDIRECT_URIS}")#;\
s#CLIENT_SECURITY_ADMIN_CONSOLE_WEB_ORIGINS#$(echo -n "${CLIENT_SECURITY_ADMIN_CONSOLE_WEB_ORIGINS}")#;\
s#SMTP_STARTTLS#$(echo -n "${SMTP_STARTTLS}")#;\
s#SMTP_AUTH#$(echo -n "${SMTP_AUTH}")#;\
s#SMTP_ENVELOPE_FROM#$(echo -n "${SMTP_ENVELOPE_FROM}")#;\
s#SMTP_SSL#$(echo -n "${SMTP_SSL}")#;\
s/SMTP_PASSWORD/$GMT_SMTP_PASSWORD/;\
s#SMTP_PORT#$(echo -n "${SMTP_PORT}")#;\
s#SMTP_HOST#$(echo -n "${SMTP_HOST}")#;\
s#SMTP_REPLY_TO_DISPLAY_NAME#$(echo -n "${SMTP_REPLY_TO_DISPLAY_NAME}")#;\
s#SMTP_REPLY_TO#$(echo -n "${SMTP_REPLY_TO}")#;\
s#SMTP_FROM_DISPLAY_NAME#$(echo -n "${SMTP_FROM_DISPLAY_NAME}")#;\
s#SMTP_FROM#$(echo -n "${SMTP_FROM}")#;\
s#SMTP_USER#$(echo -n "${SMTP_USER}")#;\

" \
/tmp/gmt-realm.json.template > /tmp/gmt-realm.json
